### ISSUE TITLE
Availability on Polygon ?

### ISSUE THREAD

**Issue by GaloisField2718** [Shard-Labs/PoLido#77]
Hello everyone,

I have a question about Polygon Network.

When contracts will be deployed on Polygon Network to be use into it ?

Thanks for you're reading, have a nice day 🙂

**Comment by GaloisField2718** [comment]
> Unsupported chain. Polygon staking and Lido contracts are deployed on Ethereum. Please switch to Mainnet in your wallet
On [polygon.lido.fi](https://polygon.lido.fi/)

**Comment by DeFiYaco** [comment]
It will never be deployed on Polygon due to the Polygon's network architecture.
Polygon native staking contracts are deployed on Ethereum mainnet.
https://wiki.polygon.technology/docs/maintain/validator/architecture

**Comment by GaloisField2718** [comment]
Okay thank you for your feedback I didn’t know. I will check it deeper.
